M48
; DRILL file KiCad 10.0.3 date 2026-06-19T14:35:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-19T14:35:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X111.397Y-104.246
X111.397Y-109.096
T2
X108.367Y-103.946
X108.367Y-109.396
M30
